---
- name: Install nginx repo files
  template:
    src: nginx.repo
    dest: /etc/yum.repos.d/
    mode: 0644
  when: ansible_distribution == 'CentOS'

- name: Install nginx package
  yum:
    name: nginx
    state: present

- name: Create the nginx log directory
  file:
    path: /var/log/nginx
    state: directory
    owner: deploy
    group: deploy
    mode: 0755

- name: Create nginx conf.d/upstreams directory
  file:
    path: /etc/nginx/conf.d/upstreams
    state: directory
    mode: 0755
    owner: root
    group: root

- name: Create nginx conf.d/locations directory
  file:
    path: /etc/nginx/conf.d/locations
    state: directory
    mode: 0755
    owner: root
    group: root

- name: Create nginx conf.d/servers directory
  file:
    path: /etc/nginx/conf.d/servers
    state: directory
    mode: 0755
    owner: root
    group: root
