namespace: "arnoldclark"
name: "rails_applications"
version: "1.0.0"
readme: "README.md"
authors:
    - "archops (archops@arnoldclark.com)"
dependencies:
license:
    - "MIT"
tags:
    - demo
    - collection
repository: "git@github.com:ac-obair/rails-application-roles-collection.git"
