---
- name: start-nginx
  service: name=nginx state=started enabled=yes

- name: restart-nginx
  service: name=nginx state=restarted enabled=yes

- name: reload-nginx
  service: name=nginx state=reloaded enabled=yes

- name: reload-firewalld
  command: "firewall-cmd --reload"
