- name: Rotate application logs for {{ application }}
  template:
    src: application-logs.j2
    dest: "/etc/logrotate.d/{{ server }}-{{ application }}"
    owner: root
    group: root
    mode: 0644